#!/usr/bin/env bash
#this is mutiples of 3 state fizz, of 5 buzz. number 15=fizzbuzz
for num in range(1, 101):
if num % 15 is 0:
print("FizzBuzz")
       elif num % 3 is 0:
        print("Fizz")
    elif num % 5 is 0:
           print("Buzz")
        else:
	print(num)
	done
