#!/usr/bin/env bash
#using the while coding format, i am adding a break for the new line to express "hi" for "holberton school"
Holberton=0
while [ $Holberton -lt 9 ]
do echo "Holberton School";
   (( Holberton++ ))
   if [ $Holberton = 8 ]; then echo "hi";
fi;
done
