#!/usr/bin/env bash
#writing good luck and bad luck in the numbers of chinese traditions
x=1
while [ $x -le 20]
do
    case $x in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from japan"
	    ;;
	17)
	    echo "bad luck from italy"
	    ;;
	*)
	    echo "$x"
	    ;;
	esasc
	=$(( x + 1 ))
    done
