#!/usr/bin/env bash
#fun times coding
if [[ -e "holbertonschool" ]]
then
echo "holberton school file exists"

if [[ -s "holbertonschool" ]]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is emptyy"

fi

if [[ -f "holbertonschool" ]]
then
echo "holbertonschool is regular file"

fi
else
echo "holbertonschool file does not exist"
fi
